### PR TITLE
[JENKINS-56079] Print the classpath in case of a ClassNotFoundException

### PR DESCRIPTION
**Pull request by carlossg**
When building projects on top of jenkinsfile-runner if you pass the wrong directories it just thows ClassNotFoundException with no hints to what's wrong

eg. https://github.com/carlossg/jenkinsfile-runner-lambda/blob/master/src/main/java/org/csanchez/jenkins/lambda/Handler.java#L172

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@carlossg could you please create a JIRA ticket and explain how you got into this situation in it?

**Comment by varyvol** [comment]
Yes, I'm confused because that class is from the Jenkinsfile Runner itself, so it's not something that should fail.

**Comment by carlossg** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-56079

**Review by varyvol — COMMENTED** [review]
@carlossg thanks! I was not aware of that kind of usage of the tool.

**Review by varyvol — APPROVED** [review]

**Review by fcojfernandez — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
error message could be formatted better, but LGTM

**Pull request merged**
