### PR TITLE
[JENKINS-54351] Avoid skipping enforcer in builds

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-54351](https://issues.jenkins-ci.org/browse/JENKINS-54351)

Avoid skipping the enforcer in builds. Exclude a couple dependencies that were raising upper bound errors.

@oleg-nenashev @fcojfernandez

### CODE REVIEW

**Comment by varyvol** [comment]
@oleg-nenashev I executed the CWP demo and everybody seems fine. Any other test that you think could be useful to execute here?

**Review by fcojfernandez — APPROVED** [review]

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
De-facto versions from the core will be used in Jenkins. So it rather hides the problem than solves it.

**Comment by varyvol** [comment]
@oleg-nenashev I avoided exclusions by reducing the versions, but I don't have context on why those were used.

**Review by oleg-nenashev — APPROVED** [review]
AFAICT there is nothing specific in args4j which would be needed here: https://github.com/kohsuke/args4j/compare/args4j-site-2.0.31...args4j-site-2.33

Would make sense to bump Jenkins, but no immediate need to do that

**Comment by oleg-nenashev** [comment]
Thanks @varyvol !

**Pull request merged**
