### PR TITLE
Fails to compile without this

### PR DESCRIPTION
**Pull request by snoopdave**
Without this change I get this error when building via `mvn`

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.314 s
[INFO] Finished at: 2021-06-11T11:07:12-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bootstrap: Compilation failure: Compilation failure:
[ERROR] /Users/dave/src.cloudbees/battleship/jenkinsfile-runner/bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsLauncherCommand.java:[30,24] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: package javax.annotation
[ERROR] /Users/dave/src.cloudbees/battleship/jenkinsfile-runner/bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsLauncherCommand.java:[79,6] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: class io.jenkins.jenkinsfile.runner.bootstrap.commands.JenkinsLauncherCommand
[ERROR] -> [Help 1]
```

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

Add annotation-api so that `PostConstruct` annotation is defined.

- [x] Link to relevant issues in GitHub or Jira

n/a

- [x] Link to relevant pull requests, esp. upstream and downstream changes

n/a

- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
You are building JFR on Java 11. It is not supported ATM. A corrct fix would be to replace all annotations by SpotBugs ones so that there is no javax dependencies left

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Requesting change based on the feedback above. We could merge a fix as a stopgap measure, but it is rather confirming the technical debt and emphasizing licensing concerns caused by this particular library. I would rather have a proper fix if no urgent need to have a Java 11 development flow

**Comment by jglick** [comment]
see #374 also

**Comment by jglick** [comment]
> replace all annotations by SpotBugs ones

Not following. This is not a static analysis annotation. It is related to dependency injection, from Java EE, and seems to be about runtime not just building. https://github.com/jenkinsci/jenkinsfile-runner/blob/e76a4461a5f38d02d27d196cb600a6448431867e/bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsLauncherCommand.java#L79-L81

Introduced in #21. Still valid after #432, #437, etc.?

**Comment by jglick** [comment]
Since #526 was merged I think this can be closed now @snoopdave?

**Comment by snoopdave** [comment]
Yes. I will close. Thanks @oleg-nenashev and @jglick

**Pull request closed without merging**
