### PR TITLE
Add missing dep so mvn package completes without error.

### PR DESCRIPTION
**Pull request by wayneseymour**
Add the following to the dependencies.
```
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.2</version>
    </dependency>
```

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
It is really strange, because CI runs 'mvn package'. What is your build environment?

**Comment by wayneseymour** [comment]
@oleg-nenashev Hello there, I'm running a newer Mac Book Pro
Java Version:
```
openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
```

**Comment by varyvol** [comment]
@wayneseymour could you please add here the error you are getting?

**Comment by oleg-nenashev** [comment]
I am closing it, because there is no further updates from @wayneseymour .
I have also released 1.0-beta-10 today, and it redefines the build flow significantly. It worth trying the current master branch there

**Pull request closed without merging**
