### PR TITLE
Update to Jenkins LTS version 2.375

### PR DESCRIPTION
**Pull request by romanisb**
This PR is trying to address the current issues were using/building a JFR image with a Jenkins version > 2.346.3 fails (e.g. #686 or #657).

The changes are addressing:

* Jenkins refactoring from [JEP-230](https://github.com/jenkinsci/jep/tree/master/jep/230)
* Couple of dependency updates
* Refactoring of some deprecations

I have commented some dependencies were @oleg-nenashev has added a TODO to remove.
I'm not 100% sure, but they could be safely removed now.

#### Test Image
`romanisb/jenkinsfile-runner:jenkins-core-2.375.4`

*(Build from `packaging/docker/unix/eclipse-temurin-11-jre/Dockerfile`):*

##### Jenkinsfile
```groovy
node() {
    echo("${Jenkins.instance.getVersion()}")
}
```

##### Command

`docker run --rm -v ${pwd}:/workspace romanisb/jenkinsfile-runner:jenkins-core-2.375.4 -ns`

##### Output

```
...<jpi related warnings removed>
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/app/jenkins/WEB-INF/lib/groovy-all-2.4.21.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Started
Resume disabled by user, switching to high-performance, low-durability mode.
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /build
[Pipeline] {
[Pipeline] echo
2.375.4
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

### Submitter checklist

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Everything looks good, thanks you! I would likely go straight to Jetty 11 but it is a separate topic

**Comment by romanisb** [comment]
> Everything looks good, thanks you! I would likely go straight to Jetty 11 but it is a separate topic

Thanks for the approval. Before merging this change, let me remove a change which shouldn't end up in this PR and clean up the commented dependencies.

**Comment by romanisb** [comment]
Done from my side. If I find the time I'll try to look into updating Jetty to version 11, but rather in another PR.

**Comment by romanisb** [comment]
> Everything looks good, thanks you! I would likely go straight to Jetty 11 but it is a separate topic
@oleg-nenashev 

I've looked into updating to Jetty 11 and straight away the compilation will fail because auf the namespace change from `javax.*` to `jakarta.*`:

```bash
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/c/Users/dev/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java:[20,20] error: package javax.servlet does not exist
[ERROR] /mnt/c/Users/dev/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java:[21,20] error: package javax.servlet does not exist
[ERROR] /mnt/c/Users/dev/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java:[77,20] error: package javax.servlet does not exist
[ERROR] /mnt/c/Users/dev/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java:[80,14] error: cannot find symbol
  symbol:   class ServletContext
  location: class JenkinsLauncher<T>
  where T is a type-variable:
    T extends JenkinsLauncherCommand declared in class JenkinsLauncher
[ERROR] /mnt/c/Users/dev/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java:[375,23] error: cannot find symbol
  symbol:   class ServletContext
  location: class JenkinsEmbedder
[ERROR] /mnt/c/Users/dev/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/PluginManagerImpl.java:[14,29] error: cannot find symbol
  symbol:   class ServletContext
  location: class PluginManagerImpl
[ERROR] /mnt/c/Users/dev/com/romanisb/jenkinsfile-runner/setup/src/main/java/io/jenkins/jenkinsfile/runner/NoListenerConfiguration.java:[8,20] error: package javax.servlet does not exist
[INFO] 7 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jenkinsfile Runner 1.0-beta-32-SNAPSHOT:
[INFO]
[INFO] Jenkinsfile Runner ................................. SUCCESS [  1.422 s]
[INFO] bootstrap .......................................... SUCCESS [  7.175 s]
[INFO] setup .............................................. FAILURE [  7.503 s]
[INFO] Jenkinsfile Runner: Plugin dependencies ............ SKIPPED
[INFO] payload ............................................ SKIPPED
[INFO] jenkinsfile-runner ................................. SKIPPED
[INFO] packaging-parent-pom-resources ..................... SKIPPED
[INFO] packaging-parent-pom ............................... SKIPPED
[INFO] packaging-parent-pom-slim .......................... SKIPPED
[INFO] vanilla-package .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.009 s
[INFO] Finished at: 2023-07-17T10:26:19+02:00
[INFO] ------------------------------------------------------------------------
```

Also I'm not sure if Jetty 11 will somehow work with Jenkins core in the future, but I do not have that much in-depth knowledge in this:
https://www.jenkins.io/doc/administration/requirements/servlet-containers/

Tested with https://github.com/romanisb/jenkinsfile-runner/compare/update-jenkins-core-2.375...romanisb:jenkinsfile-runner:jenkins-core-2.387-jetty-11

**Comment by oleg-nenashev** [comment]
Sorry for the response delays, is definitely something to look into

**Comment by oleg-nenashev** [comment]
I hope to catch up with the discussions here but it realistically won't happen until August

**Comment by romanisb** [comment]
> I hope to catch up with the discussions here but it realistically won't happen until August

Yeah. No worries. Since this discussion is a bit off-topic with this PR, I've created a Github issue (#699), where the discussion could be continued.

**Comment by lhupfeldt** [comment]
Hi @oleg-nenashev, will there be a new (beta) release soon? I'm hoping for a fix for #686

**Comment by lhupfeldt** [comment]
Hi @oleg-nenashev, sorry to ask again, but will there be a new (beta) release soon? We have been unable to execute our pipeline tests for while.

**Comment by oleg-nenashev** [comment]
Sorry, catching up on the technical debt

**Comment by lhupfeldt** [comment]
Hi @oleg-nenashev  is the fix in beta-32?

**Comment by oleg-nenashev** [comment]
@lhupfeldt yes

**Pull request merged**
