### PR TITLE
Make https default for plugin downloads

### LINKED ISSUE #258: Use HTTPs by default for plugin downloads
Follow-up to https://github.com/jenkinsci/jenkinsfile-runner/pull/252 . Currently Jenkinsfile Runner downloads plugins via HTTP in order to get plugins from mirrors. It would be great to change defaults to HTTPs.

I would expect that runtime plugin downloads are not actively used, but it still worth fixing it.

CC @LinuxSuRen

### PR DESCRIPTION
**Pull request by sladyn98**
This PR aims to make https default for downloading plugins.
Closes: https://github.com/jenkinsci/jenkinsfile-runner/issues/258

### CODE REVIEW

**Comment by sladyn98** [comment]
The mirrors still do not support https so I am unsure if it does not find would it default to http 
CC @oleg-nenashev @LinuxSuRen

**Comment by LinuxSuRen** [comment]
I guess we still need to wait until HTTPS is ok.

**Comment by oleg-nenashev** [comment]
Yes, I suggest putting it on hold until the new Mirror infra is rolled out. CC @olblak 
FTR https://issues.jenkins-ci.org/browse/INFRA-2516

**Comment by rsvoboda** [comment]
@oleg-nenashev / @sladyn98 I think this can be rebased and `on-hold` label removed, INFRA-2516 is resolved

**Comment by oleg-nenashev** [comment]
Agreed @rsvoboda

**Comment by oleg-nenashev** [comment]
It worth mentioning that this code will be removed once [Plugin Installation Manager Tool](https://github.com/jenkinsci/plugin-installation-manager-tool) is integrated in #324. I am not a big fan of using on-demand plugin download even with that tool, in the most of cases it is better package plugins in the Build Time while packaging custom JFR images. Good for some demos though

**Review by olblak — APPROVED** [review]
\o/ No more HTTP

**Review by oleg-nenashev — APPROVED** [review]
Works on my machine (c). I added test coverage in #391 , but this is not a right time to spend too much time on tests for this feature. Tests will be a must when integrating Plugin Installation Manager

**Pull request merged**
