### PR TITLE
#180 - Modify -v/--version flag to display the version + Use `-jv/--jenkinsVersion` for the former behavior

### PR DESCRIPTION
**Pull request by mvarendorff**
This PR changes the functionality of the previous -v/--version flag (which is now called -jv/--jenkins-version) to display the version of the jenkinsfile-runner.

A few notes:

 - I hope I got all correct occurences of the "old" -v flag in the readme
 - I did *not* change version yet as this is a breaking change and did not want to change the wrong things
 - I added a new variable for the version which would be hardcoded and would have to be changed. I couldn't find any config file and parsing the pom.xml surely is not the way to go :P If there is a proper place where I would get the version number from otherwise, I will gladly change the code to do so.

### CODE REVIEW

**Comment by mvarendorff** [comment]
I hope that the change I made is what you meant; that was the simplest I could come up with without starting to mess with maven plugins etc.

**Review by oleg-nenashev — APPROVED** [review]
It should do the job, thanks! I will test it manually and then merge it. CI is in a bad shape now unfortunately because of the Vanilla packaging problem

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkinsfile-runner/issues/185 ftr

**Review by oleg-nenashev — APPROVED** [review]
Everything should be aligned now, sorry for some non-related commits after the merge conflict resolution

**Comment by mvarendorff** [comment]
No worries! Thanks for the opportunity to work on this and a PR that feels good for hacktoberfest :)

**Pull request merged**
