### PR TITLE
[JEP-305] - Publish incremental releases for pull requests

### PR DESCRIPTION
**Pull request by jglick**
Cannot really test since I lack write access, so `Jenkinsfile` will not be run from this PR. Needs someone with write access to file a copy as a draft PR.

### CODE REVIEW

**Comment by jglick** [comment]
```console
$ mvn clean install -Dset.changelist -DskipTests -Denvironment=test -Ppackage-app,package-vanilla,jacoco && (cd ~/.m2/repository/io/jenkins/jenkinsfile-runner; find * -type f -name '*-rc*' | xargs du -h | sort -n)
…
1.3M	jenkinsfile-runner/1.0-beta-30-rc743.a1a459dc53b2/jenkinsfile-runner-1.0-beta-30-rc743.a1a459dc53b2.jar
1.3M	jenkinsfile-runner/1.0-beta-30-rc743.a1a459dc53b2/jenkinsfile-runner-1.0-beta-30-rc743.a1a459dc53b2.zip
4.0K	jenkinsfile-runner/1.0-beta-30-rc743.a1a459dc53b2/jenkinsfile-runner-1.0-beta-30-rc743.a1a459dc53b2-sources.jar
4.0K	packaging-parent-pom-resources/1.0-beta-30-rc743.a1a459dc53b2/packaging-parent-pom-resources-1.0-beta-30-rc743.a1a459dc53b2-assembly-zip-config.xml
4.0K	packaging-parent-pom-resources/1.0-beta-30-rc743.a1a459dc53b2/packaging-parent-pom-resources-1.0-beta-30-rc743.a1a459dc53b2-jenkins-properties.xml
4.0K	payload-dependencies/1.0-beta-30-rc743.a1a459dc53b2/payload-dependencies-1.0-beta-30-rc743.a1a459dc53b2-sources.jar
4.0K	vanilla-package/1.0-beta-30-rc743.a1a459dc53b2/vanilla-package-1.0-beta-30-rc743.a1a459dc53b2.jar
8.0K	bootstrap/1.0-beta-30-rc743.a1a459dc53b2/bootstrap-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	jenkinsfile-runner/1.0-beta-30-rc743.a1a459dc53b2/jenkinsfile-runner-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	packaging-parent-pom/1.0-beta-30-rc743.a1a459dc53b2/packaging-parent-pom-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	packaging-parent-pom-resources/1.0-beta-30-rc743.a1a459dc53b2/packaging-parent-pom-resources-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	packaging-parent-pom-slim/1.0-beta-30-rc743.a1a459dc53b2/packaging-parent-pom-slim-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	parent/1.0-beta-30-rc743.a1a459dc53b2/parent-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	payload/1.0-beta-30-rc743.a1a459dc53b2/payload-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	payload-dependencies/1.0-beta-30-rc743.a1a459dc53b2/payload-dependencies-1.0-beta-30-rc743.a1a459dc53b2.jar
8.0K	payload-dependencies/1.0-beta-30-rc743.a1a459dc53b2/payload-dependencies-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	setup/1.0-beta-30-rc743.a1a459dc53b2/setup-1.0-beta-30-rc743.a1a459dc53b2.pom
8.0K	vanilla-package/1.0-beta-30-rc743.a1a459dc53b2/vanilla-package-1.0-beta-30-rc743.a1a459dc53b2.pom
12K	payload/1.0-beta-30-rc743.a1a459dc53b2/payload-1.0-beta-30-rc743.a1a459dc53b2-sources.jar
20K	bootstrap/1.0-beta-30-rc743.a1a459dc53b2/bootstrap-1.0-beta-30-rc743.a1a459dc53b2-sources.jar
20K	payload/1.0-beta-30-rc743.a1a459dc53b2/payload-1.0-beta-30-rc743.a1a459dc53b2.jar
20K	payload-dependencies/1.0-beta-30-rc743.a1a459dc53b2/payload-dependencies-1.0-beta-30-rc743.a1a459dc53b2.hpi
24K	payload-dependencies/1.0-beta-30-rc743.a1a459dc53b2/payload-dependencies-1.0-beta-30-rc743.a1a459dc53b2-javadoc.jar
32K	bootstrap/1.0-beta-30-rc743.a1a459dc53b2/bootstrap-1.0-beta-30-rc743.a1a459dc53b2.jar
32K	setup/1.0-beta-30-rc743.a1a459dc53b2/setup-1.0-beta-30-rc743.a1a459dc53b2-sources.jar
44K	setup/1.0-beta-30-rc743.a1a459dc53b2/setup-1.0-beta-30-rc743.a1a459dc53b2.jar
60K	payload/1.0-beta-30-rc743.a1a459dc53b2/payload-1.0-beta-30-rc743.a1a459dc53b2-javadoc.jar
124K	bootstrap/1.0-beta-30-rc743.a1a459dc53b2/bootstrap-1.0-beta-30-rc743.a1a459dc53b2-javadoc.jar
124K	setup/1.0-beta-30-rc743.a1a459dc53b2/setup-1.0-beta-30-rc743.a1a459dc53b2-javadoc.jar
```

**Comment by jglick** [comment]
#450 suggests that `jenkinsfile-runner-*.jar` is not useful? But it is still being published e.g. as https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/jenkinsfile-runner/1.0-beta-29/jenkinsfile-runner-1.0-beta-29.jar so this does not make sense. If no one is consuming it, the POM should be adjusted to not `install` or `deploy` it.

**Review by oleg-nenashev — APPROVED** [review]
Thanks!

**Review by oleg-nenashev — APPROVED** [review]
Note that JFR produces pretty big artifacts. It became better with Slim packaging and app rework, but I intend to recover the Uber JAR mode. That artifact will be around 100Mb at least, and we've already had issues with Artifactory disk usage. I would like to get feedback from the Infra team before merging it.

**Comment by oleg-nenashev** [comment]
CC @daniel-beck @olblak @dduportal @MarkEWaite  Infra feedback is needed

**Comment by MarkEWaite** [comment]
@oleg-nenashev my understanding is that the artifactory hosting concerns were more related to download traffic than use of disc space.

Are the large artifacts likely to be downloaded from artifactory or will they be available from the Jenkins mirrors (as in https://get.jenkins.io/ )?  If only from artifactory, is there a way that we could distribute them through the Jenkins mirrors ?

**Comment by oleg-nenashev** [comment]
> If only from artifactory, is there a way that we could distribute them through the Jenkins mirrors ?

There is support for artifacts on GitHub Releases already in this repo. I would not move them to the mirrors unless there is a strong use-cases for that. Technically we could just stop big artifacts from being published on Artifactory at all. The builds are reproducible, and GitHub releases should be good enough as source of truth for distribution ZIPs

**Comment by jglick** [comment]
What is this 100Mb überjar?

I know of a project consuming three artifacts from here, via Artifactory:

* `jenkinsfile-runner.zip`
* `payload.jar`
* `setup.jar`

which could presumably benefit from being able to pick up incremental releases of at least those. As you can see from https://github.com/jenkinsci/jenkinsfile-runner/pull/525#issuecomment-861067960, the only artifact of significant size not being consumed is `jenkinsfile-runner.jar`. As in https://github.com/jenkinsci/jenkinsfile-runner/pull/525#issuecomment-861077832, if there are no Maven consumers of that JAR, we could simply omit it from deployment (both incremental and regular releases).

**Comment by oleg-nenashev** [comment]
Whatever. Let's merge and see. If there is high disk usage, we will adjust

**Comment by jglick** [comment]
> Needs someone with write access to file a copy as a draft PR.

Looks like it worked after merge: https://repo.jenkins-ci.org/incrementals/io/jenkins/jenkinsfile-runner/jenkinsfile-runner/1.0-beta-30-rc748.178e51f2df47/

**Pull request merged**
