### PR TITLE
WorkflowJob.resumeBlocked = true

### PR DESCRIPTION
**Pull request by jglick**
There can be no resuming in JFR mode, so do not even pretend.
As a side effect this sets PERFORMANCE_OPTIMIZED as before.

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
There might be resuming Pipeline in the future with external Pipeline stage storage, but not now. Thanks for the patch @jglick !

**Comment by jglick** [comment]
Context: [JENKINS-63706](https://issues.jenkins-ci.org/browse/JENKINS-63706)

**Comment by oleg-nenashev** [comment]
@jglick could you please suggest a changelog entry? I can try measuring the performance difference, But I am not sure that anything changes in practice after looking into the code of the current implementations.

**Comment by jglick** [comment]
> I am not sure that anything changes in practice

Not sure if anything does now, but with https://github.com/jenkinsci/workflow-cps-plugin/pull/377 it would.

**Pull request merged**
