### PR TITLE
Cleanup "Hudson" references in the Jenkinsfile Runner codebase

### LINKED ISSUE #375: Replace "Hudson" by "Jenkins" in the codebase
There is some old Jenkinsfile Runner code which was originally a part of Jenkins test frameworks. This code uses the "Hudson" name though Jenkins was renamed to Hudson in 2011. It would be great to cleanup this code. Some occurences: https://github.com/jenkinsci/jenkinsfile-runner/search?q=Hudson

Acceptance criteria:

* "Hudson" occurrences in the documentation, Javadoc and comments are replaced with Jenkins
* "Hudson" occurrences in class and method names are replaced by "Jenkins". In this repository binary compatibility is not a concern even for public classes

### PR DESCRIPTION
**Pull request by darkphoenix17**
Contributes to #375

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
It is definitely a net improvement. Thanks for your contribution @darkphoenix17 !

**Comment by oleg-nenashev** [comment]
@darkphoenix17 if you are interested, a similar patch could be applied to the Jenkins Test harness codebase: https://github.com/jenkinsci/jenkins-test-harness which was originator of the code. Note that there Binary compatibility should be retained, so it is not possible to just rename classes and methods

**Comment by darkphoenix17** [comment]
@oleg-nenashev can this PR be eligible for _hacktoberfest_? If so, Can you add the _hacktoberfest_ label?

**Comment by darkphoenix17** [comment]
> 
> 
> @darkphoenix17 if you are interested, a similar patch could be applied to the Jenkins Test harness codebase: https://github.com/jenkinsci/jenkins-test-harness which was originator of the code. Note that there Binary compatibility should be retained, so it is not possible to just rename classes and methods

Yeah, I am very much interested. Looking forward to the issue.

**Comment by darkphoenix17** [comment]
> @darkphoenix17 if you are interested, a similar patch could be applied to the Jenkins Test harness codebase: https://github.com/jenkinsci/jenkins-test-harness which was originator of the code. Note that there Binary compatibility should be retained, so it is not possible to just rename classes and methods

Hello @oleg-nenashev , I looked through the code base and tried to understand the workflow so that I can make the necessary changes of the name.
The code of that repo is more complex than the current repo which I was working on.... could you provide me some initial steps to start working on in some form of bullets task.
Also can you open an issue and assign it to me to that i can make a PR.
Waiting for your reply!!!

**Pull request merged**
