### PR TITLE
added brew formula

### PR DESCRIPTION
**Pull request by jamesalbert**
I'm not sure what your plans for release are, but this might make it more easily to get up and running. I was able to install from my repo with the commands added to the readme (replacing "kohsuke" with my name):
```
brew tap kohsuke/jenkinsfile-runner https://github.com/kohsuke/jenkinsfile-runner.git
brew install --HEAD kohsuke/jenkinsfile-runner/jenkinsfile-runner
```

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Should be replaced by `jenkins/jenkinsfile-runner`, but generally it makes sense to have it merged IMO. Thanks @jamesalbert !

**Comment by BradleyAllanDavis** [comment]
Can we get this merged?

**Comment by jdsalchow** [comment]
This would be nice!

**Comment by oleg-nenashev** [comment]
Is someone is interested in it? If so, it would be great if you could cleanup the repository naming and submit a follow-up pull request.

**Comment by michaelneale** [comment]
Follow up pull request has been done

**Pull request closed without merging**
